spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cbbloxxxindore/config-server
  application:
    name: config-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8989

